//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class radnik
    {
        public int Id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public int maticni { get; set; }
        public int sektorId { get; set; }
    
        public virtual sektor sektor { get; set; }
    }
}
